#!/usr/bin/env python3
import urllib.request
import json
from datetime import datetime
from zoneinfo import ZoneInfo

def get_expiration_date(domain: str):
    url = f"https://rdap.org/domain/{domain}"
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as response:
        body = response.read().decode()
        data = json.loads(body)
        for event in data["events"]:
            if event["eventAction"] == "expiration":
                return datetime.fromisoformat(event["eventDate"])

domains = [
    "justinkidd.ca",
    "bytenest.ca",
    "justinharrison.ca",
    "potatolab.ca",
    "potatodns.ca",
    "potatodiet.ca",
    "jmk453.dev",
    "yeonsuchoi.ca"
]
expirations = []
for domain in domains:
    expiration_date = get_expiration_date(domain)
    expiration_date = expiration_date.astimezone(ZoneInfo("America/Toronto"))
    expirations.append((domain, expiration_date))
expirations.sort(key=lambda x: x[1])
for expiration in expirations:
    print(f"{expiration[0]} = {expiration[1]}")
