#!/usr/bin/env fish
set --local f1 /mnt/nvme/documents/Passwords.kdbx
set --local f2 /var/www/potatolab.ca/webdav/Passwords.kdbx
set --local tmpfile /tmp/syncp-tmpfile
if test "$f1" -nt "$f2"
    cp -p "$f1" "$tmpfile"
    chown http:http "$tmpfile"
    mv "$tmpfile" "$f2"
else if test "$f2" -nt "$f1"
    cp -p "$f2" "$tmpfile"
    chown justin:justin "$tmpfile"
    mv "$tmpfile" "$f1"
end
