#!/usr/bin/env python
# yarn-to-ebuild PATH_TO_YARN_LOCKFILE
import sys

def get_name(line: str):
    line = line.removeprefix('"')
    idx = line.index("@", 1)
    return line[:idx]

def get_version(line: str):
    return line.split('"', 2)[1]

with open(sys.argv[1], "r") as file:
    package = ""
    state = 0
    for line in file:
        line = line.strip()
        match state:
            case 0:
                if line == "":
                    state = 1
            case 1:
                if line == "":
                    state = 2
            case 2:
                package = get_name(line)
                state = 3
            case 3:
                package += "@" + get_version(line)
                print(package)
                state = 1
